---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: quarkus-app
  name: quarkus-app
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: quarkus-app
  name: quarkus-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    app: quarkus-app
    deploymentconfig: quarkus-app
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: quarkus-app
        deploymentconfig: quarkus-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/pipeline-test/quarkus-app:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: quarkus-app
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ImageChange
    imageChangeParams:
      containerNames:
      - quarkus-app
      from:
        kind: ImageStreamTag
        name: quarkus-app:latest
        namespace: pipeline-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-app
  name: quarkus-app
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-app
    deploymentconfig: quarkus-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: quarkus-app
  name: quarkus-app
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: quarkus-app
